// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_SnJE_i2oF0qClGW2pkVdrB3wQ7TQ8fM',
    appId: '1:550745643577:web:8845e1e1698096ff2fcbe8',
    messagingSenderId: '550745643577',
    projectId: 'just-chat-c901a',
    authDomain: 'just-chat-c901a.firebaseapp.com',
    storageBucket: 'just-chat-c901a.firebasestorage.app',
    measurementId: 'G-N23S4D4Y4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbbSsLIO3qHf78lsOObDj5T1Jz6FlyiS0',
    appId: '1:550745643577:android:12820e1494e0a9662fcbe8',
    messagingSenderId: '550745643577',
    projectId: 'just-chat-c901a',
    storageBucket: 'just-chat-c901a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYOhKsaw03wOKRASghrDavLQquoP7EAPI',
    appId: '1:550745643577:ios:3c2c994656f021382fcbe8',
    messagingSenderId: '550745643577',
    projectId: 'just-chat-c901a',
    storageBucket: 'just-chat-c901a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYOhKsaw03wOKRASghrDavLQquoP7EAPI',
    appId: '1:550745643577:ios:3c2c994656f021382fcbe8',
    messagingSenderId: '550745643577',
    projectId: 'just-chat-c901a',
    storageBucket: 'just-chat-c901a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_SnJE_i2oF0qClGW2pkVdrB3wQ7TQ8fM',
    appId: '1:550745643577:web:217725bbca24bb5c2fcbe8',
    messagingSenderId: '550745643577',
    projectId: 'just-chat-c901a',
    authDomain: 'just-chat-c901a.firebaseapp.com',
    storageBucket: 'just-chat-c901a.firebasestorage.app',
    measurementId: 'G-XXNT00PJVG',
  );
}
